services:
  app:
    container_name: frontend-app
    image: "mcr.microsoft.com/devcontainers/javascript-node:1.1.0-18-bullseye"

    volumes:
      - ../..:/workspace
      - /workspace/src/frontend/node_modules/

    ports:
      - 3000:3000

    command: /bin/sh -c "while sleep 1000; do :; done"
