services:
  todo-app-backend:
    container_name: backend
    depends_on:
      - todo_app_postgres
    build:
      context: ./src/backend
      args:
        - FRAMEWORK=flask
    command:
      [
        "sh",
        "-c",
        "pip install debugpy -t /tmp && poetry run python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn app.app:app --reload --host 0.0.0.0 --port 5000"
      ]
    ports:
      - 5000:5000
      - 5678:5678
    restart: unless-stopped
    volumes:
      # this binds the host folder to the container folder
      - ./src/backend/app:/app/app
      # the json database will be stored in /database/json_database,
      # in the data volume
      - data:/database/json_database
    environment:
      # in the container, saves the database in this path
      # - DATABASE=json
      # - DATABASE_PATH=/database/json_database
      - DATABASE=postgresql
      - DB_DIALECT=postgresql
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgres_db
      - DB_PORT=5432
      - DB_NAME=todo_db

  todo-app-frontend:
    container_name: frontend
    build:
      context: ./src/frontend
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./src/frontend/:/app/frontend/
      # avoid copying the node_modules folder from local to the container
      - /app/frontend/node_modules/
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true # allows hot reload on windows

  todo_app_postgres:
    container_name: postgres_db
    image: postgres:15.1-alpine
    restart: unless-stopped
    volumes:
      - postgres_db:/database/postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todo_db

# the path of data won't be erased on rebuild
volumes:
  data:
  postgres_db:
    driver: local
