version: '3.8'

services:
  todo-app-backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./src/backend/Dockerfile
    ports:
      - 5000:5000
    working_dir: /app/backend
    volumes:
      # this binds the host folder to the container folder
      - ./src/backend/app:/app/backend/app
      # the json database will be stored in /database/json_database,
      # in the data volume
      - data:/database/json_database
    environment:
      # in the container, saves the database in this path
      - DATABASE_PATH=/database/json_database
      - FLASK_APP=app/app.py
      - FLASK_ENV=development

  todo-app-frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./src/frontend/Dockerfile
    ports:
      - 3000:3000
    working_dir: /app/frontend/
    volumes:
      - ./src/frontend/:/app/frontend/
      # avoid copying the node_modules folder from local to the container
      - /app/frontend/node_modules/
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true # allows hot reload on windows

  todo_app_postgres:
    container_name: postgres_db
    image: postgres:15.1-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_db:/database/postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
# the path of data won't be erased on rebuild
volumes:
  data:
  postgres_db:
    driver: local
