version: '3.8'

services:
  todo-app:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    working_dir: /app/backend
    volumes:
      # the json database will be stored in /database/json_database,
      # in the data volume
      - data:/database/json_database
    environment:
      # in the container, saves the database in this path
      - DATABASE_PATH=/database/json_database
      - FLASK_APP=app/app.py
      - FLASK_ENV=production

# the path of data won't be erased on rebuild
volumes:
  data:
