global:
  scrape_interval: 60s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'backend'
    scrape_interval: 5s
    static_configs:
      - targets: ['backend:5000']
