# Testing
[tool.pytest.ini_options]
testpaths = [
    "src/backend/tests"
]

# Formatting
[tool.black]
line-length = 79

[tool.flake8]
exclude = [
    "venv/"
]

[tool.isort]
profile = "black"
line_length = 79