volumes:
  postgres-data:
  venv:


services:
  app:
    container_name: backend-app
    image: "mcr.microsoft.com/devcontainers/python:1-3.11-bullseye"

    volumes:
      - ../..:/workspace
      - venv:/workspace/src/backend/.venv

    environment:
      - FRAMEWORK=fastapi
      - DATABASE=postgresql
      - DB_DIALECT=postgresql
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgres_db
      - DB_PORT=5432
      - DB_NAME=app_db
      - OTEL_SERVICE_NAME=todo_app_backend
      - OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED=true
      - OTEL_TRACES_EXPORTER=console
      - OTEL_METRICS_EXPORTER=console
      - OTEL_LOGS_EXPORTER=console

    command: /bin/sh -c "while sleep 1000; do :; done"

  postgres:
    container_name: postgres_db
    image: postgres:15.1-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/database/postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app_db
