apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    isDefault: true
    access: proxy
    editable: true
    jsonData:
      timeInterval: 5s
  - name: Postgres
    type: postgres
    url: http://todo_app_postgres:5432
    user: postgres
    access: proxy
    editable: true
    jsonData:
      sslmode: disable
      database: todo_db
      timeInterval: 5s
    secureJsonData:
      password: postgres
  - name: Tempo
    type: tempo
    access: proxy
    orgId: 1
    url: http://tempo:3200
    basicAuth: false
    version: 1
    editable: true
    apiVersion: 1
  #   uid: tempo
  #   jsonData:
  #     httpMethod: GET
  #     serviceMap:
  #       datasourceUid: prometheus
  #     streamingEnabled: 
  #       search: true
