name: Backend Static Code Analysis
run-name: Backend SCA
on:
  push:
    paths:
      - src/backend/**
      - .github/workflows/*_backend.yml

jobs:
  run-checks:
    defaults:
      run:
        working-directory: src/backend
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres_db:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: app_db
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Install python
        uses: actions/setup-python@v6
        with:
          python-version-file: src/backend/pyproject.toml

      - name: Enable caching
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
 
      - name: Install dependencies
        run: uv sync
      # TODO: learn how to cache all previous work and use it in different jobs
      - name: Check ruff
        run: uv run ruff check .

      - name: Check black
        run: uv run black --check .

      - name: Check pyright
        run: uv run pyright .

      - name: Run tests
        run: uv run pytest
        env:
          DB_TEST_HOST: localhost

