name: Static Code Analysis
run-name: Backend SCA
on:
  [push]:
    paths:
      - src/backend/**
jobs:
  Setup-repo:
    defaults:
      run:
        working-directory: src/backend
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_todo_db
        ports:
          - 2345:5432
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version-file: src/backend/.python-version
          cache: poetry

      - name: Install dependencies
        run: poetry install
      # TODO: learn how to cache all previous work and use it in different jobs

      - name: Check ruff
        run: poetry run ruff check .

      - name: Check black
        run: poetry run black --check .

      - name: Check pyright
        run: poetry run pyright .

      - name: Run tests
        run: poetry run pytest
